# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotify.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'spotify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rspotify.proto\x12\x07spotify\"\x07\n\x05\x45mpty\"2\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\"3\n\x06Musica\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"8\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nusuario_id\x18\x03 \x01(\x05\"$\n\x0eUsuarioRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\x05\"&\n\x0fPlaylistRequest\x12\x13\n\x0bplaylist_id\x18\x01 \x01(\x05\"\"\n\rMusicaRequest\x12\x11\n\tmusica_id\x18\x01 \x01(\x05\"6\n\x10UsuariosResponse\x12\"\n\x08usuarios\x18\x01 \x03(\x0b\x32\x10.spotify.Usuario\"3\n\x0fMusicasResponse\x12 \n\x07musicas\x18\x01 \x03(\x0b\x32\x0f.spotify.Musica\"9\n\x11PlaylistsResponse\x12$\n\tplaylists\x18\x01 \x03(\x0b\x32\x11.spotify.Playlist2\xfa\x02\n\x0eSpotifyService\x12;\n\x0eListarUsuarios\x12\x0e.spotify.Empty\x1a\x19.spotify.UsuariosResponse\x12\x39\n\rListarMusicas\x12\x0e.spotify.Empty\x1a\x18.spotify.MusicasResponse\x12P\n\x19ListarPlaylistsPorUsuario\x12\x17.spotify.UsuarioRequest\x1a\x1a.spotify.PlaylistsResponse\x12N\n\x18ListarMusicasPorPlaylist\x12\x18.spotify.PlaylistRequest\x1a\x18.spotify.MusicasResponse\x12N\n\x18ListarPlaylistsPorMusica\x12\x16.spotify.MusicaRequest\x1a\x1a.spotify.PlaylistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_USUARIO']._serialized_start=35
  _globals['_USUARIO']._serialized_end=85
  _globals['_MUSICA']._serialized_start=87
  _globals['_MUSICA']._serialized_end=138
  _globals['_PLAYLIST']._serialized_start=140
  _globals['_PLAYLIST']._serialized_end=196
  _globals['_USUARIOREQUEST']._serialized_start=198
  _globals['_USUARIOREQUEST']._serialized_end=234
  _globals['_PLAYLISTREQUEST']._serialized_start=236
  _globals['_PLAYLISTREQUEST']._serialized_end=274
  _globals['_MUSICAREQUEST']._serialized_start=276
  _globals['_MUSICAREQUEST']._serialized_end=310
  _globals['_USUARIOSRESPONSE']._serialized_start=312
  _globals['_USUARIOSRESPONSE']._serialized_end=366
  _globals['_MUSICASRESPONSE']._serialized_start=368
  _globals['_MUSICASRESPONSE']._serialized_end=419
  _globals['_PLAYLISTSRESPONSE']._serialized_start=421
  _globals['_PLAYLISTSRESPONSE']._serialized_end=478
  _globals['_SPOTIFYSERVICE']._serialized_start=481
  _globals['_SPOTIFYSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)
